# Generated by Django 2.0.7 on 2018-07-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180719_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselloginimage',
            name='image',
            field=models.ImageField(upload_to='login/carousel/'),
        ),
    ]
