# Generated by Django 2.0.7 on 2018-07-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180719_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselloginimage',
            name='title',
            field=models.CharField(default='Without title', max_length=100),
        ),
    ]
